/// Integration tests for backend-rust.
///
/// Each test compiles a CDDL snippet to IR then runs the Rust backend,
/// asserting on the generated source text.

use std::path::PathBuf;
use backend_rust::RustBackend;
use cddlc_codegen::{Backend, CodegenOptions};
use cddlc_ir::lower;
use cddlc_parser::parse_cddl;

fn generate(src: &str) -> String {
    let parsed  = parse_cddl(src, PathBuf::from("test.cddl")).expect("parse");
    let lowered = lower(&parsed.value, 16, 64).expect("lower");
    let opts    = CodegenOptions::default();
    let out     = RustBackend.generate(&lowered.module, &opts).expect("generate");
    out.files[1].content.clone()
}

fn generate_no_std(src: &str) -> String {
    let parsed  = parse_cddl(src, PathBuf::from("test.cddl")).expect("parse");
    let lowered = lower(&parsed.value, 16, 64).expect("lower");
    let mut opts = CodegenOptions::default();
    opts.no_std = true;
    let out = RustBackend.generate(&lowered.module, &opts).expect("generate");
    out.files[1].content.clone()
}

// ── Smoke tests ───────────────────────────────────────────────────────────────

#[test]
fn test_generates_header() {
    let code = generate("device-id = uint");
    assert!(code.contains("@generated by cddlc"));
    assert!(code.contains("use minicbor"));
}

#[test]
fn test_no_std_header() {
    let code = generate_no_std("device-id = uint");
    assert!(code.contains("cfg_attr") && code.contains("no_std"));
}

// ── Type alias ────────────────────────────────────────────────────────────────

#[test]
fn test_simple_alias() {
    let code = generate("device-id = uint");
    assert!(code.contains("pub type DeviceId = u64;"));
}

#[test]
fn test_tstr_alias() {
    let code = generate("label = tstr");
    assert!(code.contains("pub type Label = String;"));
}

#[test]
fn test_constrained_alias_newtype() {
    let code = generate("device-id = tstr .size 16");
    // Constrained alias → newtype struct
    assert!(code.contains("pub struct DeviceId"));
    assert!(code.contains("impl<'b> Decode<'b, ()> for DeviceId"));
}

#[test]
fn test_constraint_check_in_decode() {
    let code = generate("device-id = tstr .size 16");
    assert!(code.contains("val.len() == 16"));
}

#[test]
fn test_range_constraint_check() {
    let code = generate("temp = int .ge -40 .le 85");
    assert!(code.contains("pub struct Temp"));
    assert!(code.contains("-40"));
    assert!(code.contains("85"));
}

// ── Tagged types ──────────────────────────────────────────────────────────────

#[test]
fn test_tagged_alias() {
    let code = generate("timestamp = #6.1(uint)");
    assert!(code.contains("pub struct Timestamp"));
    assert!(code.contains("Tag::new(1)"));
}

#[test]
fn test_tagged_decode_verifies_tag() {
    let code = generate("timestamp = #6.1(uint)");
    assert!(code.contains("d.tag()?"));
    assert!(code.contains("unexpected CBOR tag"));
}

#[test]
fn test_tagged_encode_emits_tag() {
    let code = generate("timestamp = #6.1(uint)");
    assert!(code.contains("e.tag(minicbor::data::Tag::new(1))?"));
}

// ── Struct ────────────────────────────────────────────────────────────────────

#[test]
fn test_struct_decl() {
    let code = generate("sensor = { id: uint, label: tstr, value: float32 }");
    assert!(code.contains("pub struct Sensor {"));
    assert!(code.contains("pub id: u64,"));
    assert!(code.contains("pub label: String,"));
    assert!(code.contains("pub value: f32,"));
}

#[test]
fn test_struct_encode_impl() {
    let code = generate("sensor = { id: uint, value: float32 }");
    assert!(code.contains("impl<C> Encode<C> for Sensor"));
    assert!(code.contains("e.map(2u64)?"));
}

#[test]
fn test_struct_decode_impl() {
    let code = generate("sensor = { id: uint, value: float32 }");
    assert!(code.contains("impl<'b> Decode<'b, ()> for Sensor"));
    assert!(code.contains("let key = d.str()?"));
    assert!(code.contains("\"id\""));
}

#[test]
fn test_optional_field_is_option() {
    let code = generate("msg = { id: uint, ? label: tstr }");
    assert!(code.contains("pub label: Option<String>,"));
}

#[test]
fn test_required_field_missing_errors() {
    let code = generate("msg = { id: uint }");
    assert!(code.contains("missing field"));
}

#[test]
fn test_unknown_field_skipped() {
    let code = generate("msg = { id: uint }");
    // Unknown keys should be skipped (permissive)
    assert!(code.contains("d.skip()?"));
}

#[test]
fn test_struct_with_ref() {
    let code = generate(r#"
device-id = tstr
sensor = { id: device-id, value: float32 }
"#);
    assert!(code.contains("pub id: DeviceId,"));
}

#[test]
fn test_tagged_struct() {
    let code = generate("tagged-sensor = #6.100({ id: uint, value: float32 })");
    assert!(code.contains("Tag::new(100)"));
    assert!(code.contains("pub struct TaggedSensor"));
}

// ── Enum ──────────────────────────────────────────────────────────────────────

#[test]
fn test_string_enum_decl() {
    let code = generate(r#"status = "ok" / "warn" / "error""#);
    assert!(code.contains("pub enum Status {"));
    assert!(code.contains("Ok("));
    assert!(code.contains("Warn("));
    assert!(code.contains("Error("));
}

#[test]
fn test_string_enum_encode() {
    let code = generate(r#"status = "ok" / "warn""#);
    assert!(code.contains("impl<C> Encode<C> for Status"));
    assert!(code.contains("e.str(s.as_str())?"));
}

#[test]
fn test_string_enum_decode() {
    let code = generate(r#"status = "ok" / "warn""#);
    assert!(code.contains("impl<'b> Decode<'b, ()> for Status"));
    assert!(code.contains("d.str()?"));
}

// ── Array ─────────────────────────────────────────────────────────────────────

#[test]
fn test_array_heapless_no_std() {
    let code = generate_no_std("; @capacity 8\nreadings = [* float32]");
    assert!(code.contains("heapless::Vec<f32, 8>"));
}

#[test]
fn test_array_std_vec() {
    let parsed  = parse_cddl("; @capacity 8\nreadings = [* float32]", PathBuf::from("test.cddl")).expect("parse");
    let lowered = lower(&parsed.value, 16, 64).expect("lower");
    let mut opts = CodegenOptions::default();
    opts.alloc = cddlc_codegen::AllocStrategy::Heap;  // ← ADD THIS LINE
    let out  = RustBackend.generate(&lowered.module, &opts).expect("generate");
    let code = &out.files[1].content;
    assert!(code.contains("Vec<f32>"));
}

#[test]
fn test_array_default_capacity_no_std() {
    // No @capacity — uses default (16)
    let code = generate_no_std("readings = [* uint]");
    assert!(code.contains("heapless::Vec<u64, 16>"));
}

// ── dCBOR ─────────────────────────────────────────────────────────────────────

#[test]
fn test_dcbor_comment_in_header() {
    let parsed  = parse_cddl("s = { a: uint, b: tstr }", PathBuf::from("t.cddl")).unwrap();
    let lowered = lower(&parsed.value, 16, 64).unwrap();
    let mut opts = CodegenOptions::default();
    opts.dcbor = true;
    let out  = RustBackend.generate(&lowered.module, &opts).unwrap();
    let code = &out.files[1].content;
    assert!(code.contains("deterministic"));
}

// ── Generics ──────────────────────────────────────────────────────────────────

#[test]
fn test_generic_instantiation_emits_struct() {
    let code = generate(r#"
labeled<T> = { label: tstr, value: T }
temp-reading = labeled<float32>
"#);
    assert!(code.contains("pub struct TempReading {"));
    assert!(code.contains("pub value: f32,"));
}

// ── Real-world schema ─────────────────────────────────────────────────────────

#[test]
fn test_iot_schema_generates() {
    let code = generate(r#"
sensor-message = {
    version:   uint,
    device-id: device-id,
    timestamp: #6.1(uint),
}
device-id = tstr .size 16
"#);
    assert!(code.contains("pub struct SensorMessage"));
    assert!(code.contains("pub struct DeviceId"));
    assert!(code.contains("val.len() == 16"));
    // Inline tags in struct fields are stripped — field type is just the inner type
    assert!(code.contains("pub timestamp: u64"));
}
